import './globals.css';
import { Commissioner } from 'next/font/google';

const commissioner = Commissioner({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={commissioner.className}>{children}</body>
    </html>
  );
}
